name: Cron Jobs

on:
  schedule:
    - cron: '*/5 * * * *'    # toutes les 5 minutes
    - cron: '0 20 * * *'     # tous les jours à 20h
  workflow_dispatch:         # pour le lancer manuellement

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run price tracking script
        run: bash script/track_price.sh

      - name: Generate daily report at 20h
        if: github.event.schedule == '0 20 * * *'
        run: bash generate_report.sh

      - name: Commit and push if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Vérifie s'il y a eu des changements
          git add data/
          if ! git diff --cached --quiet; then
            # Vérifie que le dernier commit n'est pas de GitHub Actions pour éviter une boucle
            LAST_COMMIT_AUTHOR=$(git log -1 --pretty=format:'%an')
            if [ "$LAST_COMMIT_AUTHOR" != "github-actions[bot]" ]; then
              git commit -m "Update data automatically"
              git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
            else
              echo "Dernier commit vient déjà de GitHub Actions, on ne push pas pour éviter une boucle."
            fi
          else
            echo "Aucun changement détecté, rien à push."
